### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by AriellaS** [SparkShen02/Easy-Duo-Authentication#2]
I think it would helpful if the one-time passcode would be automatically copied to clipboard when you open the chrome extension.

**Comment by AriellaS** [comment]
Nevermind, I noticed a copy button was added recently, but the version on the chrome web store doesn't have this

**Comment by SparkShen02** [comment]
Yep, thanks for pointing it out. A copy button has been added recently, and I'll update that to the web store soon.
