### ISSUE TITLE
Getting Android and Ios version upgrade error

### ISSUE THREAD

**Issue by abhijeetshuklaoist** [SparkShen02/Easy-Duo-Authentication#3]
I have been using this extension for quite some time now. But recently I had to reinstall my Chrome. 
Now when I am trying to setup this extension, setup gets successful but when I enter the token generated by extension, I get error message saying "Please update to Android 4.0 or above and try again."
<img width="629" alt="image" src="https://user-images.githubusercontent.com/15669115/177048172-6dee3e44-0d65-4ba9-a43c-62823e843b0f.png">

**Comment by SparkShen02** [comment]
Will look into that in a few days.

**Comment by abhijeetshuklaoist** [comment]
I have never written any chrome extension and I have no idea about how this extension works. Started exploring the code base a few minutes back. 
If you can guide me, maybe I can pick this up and fix it.

**Comment by SparkShen02** [comment]
Definitely! The main files are just popup.html, which determines the extension interface, and popup.js, which runs every time you open the extension. 

I also need to investigate where the “Android version” thing comes in, but I’ll probably be able to solve this in a few days.

**Comment by SparkShen02** [comment]
This has been fixed in the latest commit. I have published the update to the chrome store for review. You should be able to download the new version later this week.
