### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by raycekar** [SparkShen02/Easy-Duo-Authentication#5]
Would it be possible to support the push notification option for the browser extension?

Asking as that is the only option I can use while at work when connecting to the vpn is to have it sent me the push notification, and in fact, the normal duo page wont even show when doing the process

**Comment by SparkShen02** [comment]
This is certainly the ideal way – one-click authentication instead of requiring users to copy and paste the passcode. I've done some research and tried, but so far haven't found a way to implement this.

**Comment by SparkShen02** [comment]
Found an implementation that works: https://github.com/FreshSupaSulley/DuOSU.
