### ISSUE TITLE
QR Scanner won't work !

### ISSUE THREAD

**Issue by anantkm** [SparkShen02/Easy-Duo-Authentication#7]
Dear Team,

I am a student at UCR, and I have been greatly benefiting from your extension. Until recently, everything was working smoothly. However, after the latest update, I've encountered some issues. Specifically, the QR scanner is not compatible with our system, as UCR still uses the old portal.

I kindly request that you consider reintroducing the previous functionality, allowing us to activate the extension via a link. This would be extremely helpful for UCR students like me.

Thank you for your attention. Please do reach out to me if you have any questions.

**Comment by SparkShen02** [comment]
I will look into that. Is https://guide.duo.com/prompt the type of portal you use or an even older portal?

**Comment by anantkm** [comment]
This is the protal. Please let me know if you need more information. 

<img width="1918" alt="Screenshot 2023-05-06 at 12 23 06 AM" src="https://user-images.githubusercontent.com/45778202/236609773-76ececa5-a9e3-4aa0-92ea-81af38e29f86.png">

**Comment by SparkShen02** [comment]
Ok I’ve never seen this portal. Can you paste here the HTML source code of this page? You can delete any personal information. I just need to see the HTML elements.

**Comment by anantkm** [comment]
[DUO_SC.zip](https://github.com/SparkShen02/Easy-Duo-Authentication/files/11413045/DUO_SC.zip)
Thanks for the response. This is the source code.

**Comment by SparkShen02** [comment]
I've added back the activation link setup option. It should've been updated on the web store. Let me know if it doesn't work.

**Comment by anantkm** [comment]
Hello, I appreciate your prompt reply and for sharing the swift solution. I've given it a try on both Windows and Mac platforms. Auto Login operates smoothly on Mac OS, but unfortunately, it isn't functioning on Windows. The one-time passcode, on the other hand, works well on both systems. The Auto Login issue isn't of immediate concern.
