### ISSUE TITLE
Keep getting link no longer valid

### ISSUE THREAD

**Issue by bsule** [SparkShen02/Easy-Duo-Authentication#8]
I keep getting "seems like the activation link is no longer valid" every time i paste in the link whether its straight from the email or after clicking the link and copying from the bar. Its worked previously for me but i got a new computer and it now does not work.

**Comment by SparkShen02** [comment]
Hmm there should be no difference from the previous version. What’s the format of your link?

**Comment by bsule** [comment]
https://m-........duosecurity.com/android/........ with andriod tablet selected but i also tried ios tablet

**Comment by SparkShen02** [comment]
I’ll look into this. And just to make sure, is your organization using an older duo portal (otherwise the new QR code activation method should work)?

**Comment by bsule** [comment]
Yeah its the old duo portal and the qr code isnt working

**Comment by SparkShen02** [comment]
Yeah, there's a bug. It stops working at my end as well. I will need some time to investigate. Thanks for pointing it out.

**Comment by bsule** [comment]
it might be a change that duo did because im trying it with another chrome authenticator and it doesnt work either

**Comment by SparkShen02** [comment]
Install the latest version, and it should work now. Let me know if it doesn't.

**Comment by bsule** [comment]
yes it works, thanks!
